title: Learning by blocks
author: Guillermo Gómez
email: mlgxmez@gamil.com
description: > # this means to ignore newlines until "baseurl:"
  Thinking in writing about machine learning and everything related.

# social links
twitter_username: mlgxmez
github_username:  mlgxmez

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima

---
title: "Hello World!"
date: 2018-04-28
---

